name: Checa notebooks

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configura o Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Instala depend√™ncias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: jwalton/gh-find-current-pr@v1
        id: finder
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Check Jupyter Notebooks'
        id: checklist
        run: |
          OUTPUT=$(python scripts/ops/check_notebooks.py)
          OUTPUT="${OUTPUT//'%'/'%25'}‚Äã„Äê7,6 m„Äë"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo "::set-output name=result::$OUTPUT"
      - name: Notebook checklist
        uses: marocchino/sticky-pull-request-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.finder.outputs.pr }}
          message: |
            Obrigada pela sua contribui√ß√£o! üéâ
            ```
            ${{ steps.checklist.outputs.result }}
            ```
